# Generated by Django 6.0.7 on 2026-07-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
