# Generated by Django 6.0.7 on 2026-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_increase_slug_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="read_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
